{% set version = "3.2.0" %}

package:
  name: pytest-html
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-html/pytest-html-{{ version }}.tar.gz
  sha256: c4e2f4bb0bffc437f51ad2174a8a3e71df81bbc2f6894604e604af18fbe687c3

build:
  number: 1
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - pip

  run:
    - py >=1.8.2
    - python >=3.6
    - pytest >=5.0,!=6.0.0
    - pytest-metadata

test:
  requires:
    - pip
  imports:
    - pytest_html
  commands:
    - pip check

about:
  home: https://github.com/pytest-dev/pytest-html
  license: MPL-2.0
  license_file: LICENSE
  summary: pytest plugin for generating HTML reports

extra:
  recipe-maintainers:
    - 0xbe7a
    - birdsarah
    - davehunt
    - nicoddemus
