{% set name = "pytest-html" %}
{% set version = "2.0.0" %}
{% set hash_type = "sha256" %}
{% set hash = "1428837592c94404e4112fbae76f6e512c35aab4b7d663dc3dd6ea58d2979710" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python
    - pytest >=3.0
    - pytest-metadata

test:
  imports:
    - pytest_html

about:
  home: https://github.com/pytest-dev/pytest-html
  license: MPL 2.0
  license_file: LICENSE
  license_family: OTHER
  summary: 'pytest plugin for generating HTML reports'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
