{% set version = "4.0.0rc4" %}

package:
  name: pytest-html
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-html/pytest_html-{{ version }}.tar.gz
  sha256: 65a85883c295fb0e37f4335bacbe769d484623cbffc77da0be071d3449e4d774

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.13.0
    - hatch-vcs >=0.3.0

  run:
    - py >=1.8.2
    - python >=3.7
    - pytest >=7.0.0
    - pytest-metadata >=2.0.2
    - jinja2 >=3.0.0

test:
  requires:
    - pip
  imports:
    - pytest_html
  commands:
    - pip check

about:
  home: https://github.com/pytest-dev/pytest-html
  license: MPL-2.0
  license_file: LICENSE
  summary: pytest plugin for generating HTML reports

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
